version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"  # Port untuk akses Metabase
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=de8_final_project  # Nama database yang digunakan di MySQL
      - MB_DB_HOST=ajinusa-mysql-container  # Nama container MySQL
      - MB_DB_USER=root  # Username untuk MySQL
      - MB_DB_PASS=ajinusa  # Password untuk MySQL
      - MB_DB_PORT=3306  # Port MySQL
    restart: always
    networks:
      - ajinusa-de8-network

  # mysql:
  #   image: mysql:latest
  #   container_name: ajinusa-mysql-container
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ajinusa
  #     MYSQL_DATABASE: de8_final_project  # Nama database yang digunakan
  #     MYSQL_USER: root  # Username untuk koneksi ke MySQL
  #     MYSQL_PASSWORD: ajinusa  # Password untuk koneksi ke MySQL
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - ajinusa-de8-network
  #   restart: always
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #     - ./my.cnf:/etc/mysql/my.cnf  # Menambahkan file konfigurasi custom

networks:
    ajinusa-de8-network:
        driver: bridge
        external: true

volumes:
  mysql-data:
