services:
    ajinusa-de8-jupyter:
        container_name: ${JUPYTER_CONTAINER_NAME}
        hostname: ${JUPYTER_CONTAINER_NAME}
        image: ajinusa-de8-dibimbing/jupyter
        environment:
            - JUPYTER_ALLOW_INSECURE_WRITES=true
        ports:
            - ${JUPYTER_PORT}:8888
            - 4040:4040
            - 4041:4041
        volumes:
            - ../:/resources
            - ../notebooks:/home/jovyan/

# ajinusa-mysql-container:
#   container_name: ajinusa-mysql-container
#   image: mysql:5.7
#   environment:
#     MYSQL_ROOT_PASSWORD: ajinusa
#     MYSQL_DATABASE: de8_final_project
#   ports:
#     - "3306:3306"
#   networks:
#       - mysql-network


networks:
    default:
        name: ajinusa-de8-network
        external: true
