services:
    ajinusa-de8-postgres:
        image: postgres:11
        container_name: ${POSTGRES_CONTAINER_NAME}
        restart: unless-stopped
        hostname: ${POSTGRES_CONTAINER_NAME}
        networks:
            - ajinusa-de8-network
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ../sql:/sql
            - ../data:/data
        ports:
            - ${POSTGRES_PORT}:5432

networks:
    ajinusa-de8-network:
        driver: bridge
        external: true
